"""Models for MQTT Events."""

from .base import BaseEvent, EventType
from .operation import OperationEvent, OperationName, OperationStatus
from .service import (
    ServiceEvent,
    ServiceEventAccess,
    ServiceEventAirConditioning,
    ServiceEventChangeAccess,
    ServiceEventChangeChargeMode,
    ServiceEventChangeChargeModeData,
    ServiceEventChangeLights,
    ServiceEventChangeOdometer,
    ServiceEventChangeRemainingTime,
    ServiceEventChangeSoc,
    ServiceEventChangeSocData,
    ServiceEventCharging,
    ServiceEventChargingCompleted,
    ServiceEventChargingError,
    ServiceEventChargingStatusChanged,
    ServiceEventClimatisationCompleted,
    ServiceEventClimatisationData,
    ServiceEventData,
    ServiceEventDeparture,
    ServiceEventDepartureErrorPlug,
    ServiceEventDepartureReady,
    ServiceEventDepartureStatusChanged,
    ServiceEventError,
    ServiceEventErrorData,
    ServiceEventLights,
    ServiceEventName,
    ServiceEventOdometer,
)
from .vehicle import (
    VehicleEventAwake,
    VehicleEventConnectionOffline,
    VehicleEventConnectionOnline,
    VehicleEventData,
    VehicleEventIgnitionStatusChanged,
    VehicleEventName,
    VehicleEventVehicleIgnitionStatusData,
    VehicleEventWarningBatterylevel,
)

__all__ = [
    "BaseEvent",
    "EventType",
    "OperationEvent",
    "OperationName",
    "OperationStatus",
    "ServiceEvent",
    "ServiceEventAccess",
    "ServiceEventAirConditioning",
    "ServiceEventChangeAccess",
    "ServiceEventChangeChargeMode",
    "ServiceEventChangeChargeModeData",
    "ServiceEventChangeLights",
    "ServiceEventChangeOdometer",
    "ServiceEventChangeRemainingTime",
    "ServiceEventChangeSoc",
    "ServiceEventChangeSocData",
    "ServiceEventCharging",
    "ServiceEventChargingCompleted",
    "ServiceEventChargingError",
    "ServiceEventChargingStatusChanged",
    "ServiceEventClimatisationCompleted",
    "ServiceEventClimatisationData",
    "ServiceEventData",
    "ServiceEventDeparture",
    "ServiceEventDepartureErrorPlug",
    "ServiceEventDepartureReady",
    "ServiceEventDepartureStatusChanged",
    "ServiceEventError",
    "ServiceEventErrorData",
    "ServiceEventLights",
    "ServiceEventName",
    "ServiceEventOdometer",
    "VehicleEventAwake",
    "VehicleEventConnectionOffline",
    "VehicleEventConnectionOnline",
    "VehicleEventData",
    "VehicleEventIgnitionStatusChanged",
    "VehicleEventName",
    "VehicleEventVehicleIgnitionStatusData",
    "VehicleEventWarningBatterylevel",
]
