site_name: MySkoda
theme:
  name: readthedocs
  highlightjs: true

watch:
  - README.md

plugins:
  - autorefs
  - search
  - gen-files:
      scripts:
        - scripts/gen_ref_nav.py
  - literate-nav:
      nav_file: SUMMARY.md
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [myskoda]

nav:
  - Home: README.md
  - Fetching Data: fetching_data.md
  - Refreshing Data: refreshing_data.md
  - Events: events.md
  - Primer: primer.md
  - API reference: reference/
  - Skoda API details:
      - MQTT: mqtt.md
      - Rest API: rest.md
