---
name: Publish to PyPI

on:
  release:
    types: [published]

jobs:
  publish-to-pypi:
    name: Publish Python distribution to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/myskoda
    permissions:
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # https://docs.astral.sh/uv/guides/integration/github/#installation
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.9"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: pyproject.toml

      - name: Build and publish package
        run: |
          uv build
          uv publish
