name: Lint and test

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repository
        uses: actions/checkout@v4

      - name: Install dev dependencies
        run: sudo snap install just --classic

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.9"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: pyproject.toml

      - name: Install Python dependencies
        run: |
          uv sync --all-extras

      - name: Lint
        run: |
          just lint

      - name: Test
        run: |
          just test

      - name: Coveralls
        uses: coverallsapp/github-action@v2
        with:
          file: coverage.xml
          fail-on-error: false
