name: Lint and test

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repository
        uses: actions/checkout@v4

      # This has been done according to https://docs.makedeb.org/prebuilt-mpr/getting-started/
      # This is needed for packages: just
      - name: Add makedb debian user repository
        run: |
          curl -q 'https://proget.makedeb.org/debian-feeds/prebuilt-mpr.pub' | gpg --dearmor | sudo tee /usr/share/keyrings/prebuilt-mpr-archive-keyring.gpg 1> /dev/null
          echo "deb [signed-by=/usr/share/keyrings/prebuilt-mpr-archive-keyring.gpg] https://proget.makedeb.org prebuilt-mpr $(lsb_release -cs)" | sudo tee /etc/apt/sources.list.d/prebuilt-mpr.list
          sudo apt update

      - name: Install dev dependencies
        run: sudo apt install just

      - name: Install Poetry
        run: pipx install poetry

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: pyproject.toml
          cache: "poetry"

      - name: Install Python dependencies
        run: |
          poetry install --no-root --extras "cli docs"

      - name: Lint
        run: |
          just lint

      - name: Test
        run: |
          just test